
services:
    web:
        container_name: backend
        build: .
        command: python manage.py runserver 0.0.0.0:3000
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
        depends_on:
            - db
    
    db:
        container_name: db
        image: postgres:15
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=bookclub
            - POSTGRES_USER=bookclub_user
            - POSTGRES_PASSWORD=bookclub_password

volumes:
    postgres_data:


