# Generated by Django 5.0.1 on 2025-01-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('VOTING', 'In Voting'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('ARCHIVED', 'Archived'), ('VETOED', 'Vetoed')], default='SUGGESTED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('VETO', 'Veto')], max_length=5)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
