name: Django with Parcel CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: bookclub
          POSTGRES_USER: bookclub_user
          POSTGRES_PASSWORD: bookclub_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    # Python setup
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    # Node.js setup for frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Frontend dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Build Frontend assets
      working-directory: ./frontend
      run: npm run build
    
    # Create a settings file for GitHub Actions
    - name: Create local settings for GitHub Actions
      run: |
        cat > bookclub/local_settings.py << 'EOL'
        # Local settings for GitHub Actions
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': 'bookclub',
                'USER': 'bookclub_user',
                'PASSWORD': 'bookclub_password',
                'HOST': 'localhost',
                'PORT': 5432,
            }
        }
        EOL
    
    # Django tests and checks
    - name: Run Django migrations
      run: python manage.py migrate
      env:
        DJANGO_SETTINGS_MODULE: bookclub.settings
        DEBUG: 1
    
    - name: Run Django tests
      run: python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: bookclub.settings
        DEBUG: 1
    
    - name: Collect static files
      run: python manage.py collectstatic --noinput
      env:
        DEBUG: 0
        DJANGO_SETTINGS_MODULE: bookclub.settings
    
    # Prepare for deployment
    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r bookclub deployment/
        cp -r staticfiles deployment/
        cp manage.py deployment/
        cp -r requirements.txt deployment/
        # Add any other necessary files for deployment
    
    - name: Upload deployment artifact
      uses: actions/upload-artifact@v3
      with:
        name: django-app
        path: deployment/

  # GitHub Pages deployment job
  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Frontend dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Build Frontend for GitHub Pages
      working-directory: ./frontend
      run: npm run build:github
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: frontend/dist
        branch: gh-pages

